name: "Dev: Test & Deploy"

on:
  push:
    branches: [dev]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
      - uses: actions/checkout@v2    
      - name: Install dependencies
        run: yarn install
      - run: yarn test

  build_and_deploy:
    name: Build & deploy
    runs-on: ubuntu-latest
    needs: [tests]
    env:
      JWT_SECRET: DefaultJwtSecret
      AUTH_TOKEN: AuthenticationUser
      MONGODB_CONN_STRING: mongodb://localhost/auth
      AWS_ACCESS_KEY_ID: AKIAXPD72NWFLN34S3MA
      AWS_SECRET_ACCESS_KEY: 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
    steps:
      - uses: actions/setup-node@v2
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn build
      - run: yarn deploy --stage dev

